// <auto-generated />
using LegislativeInfoSystem.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegislativeInfoSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508201424_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("LegislationLegislator", b =>
                {
                    b.Property<int>("LegislationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SponsorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LegislationId", "SponsorsId");

                    b.HasIndex("SponsorsId");

                    b.ToTable("LegislationLegislator");
                });

            modelBuilder.Entity("LegislativeInfoSystem.Entities.Legislation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegislationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Legislation");
                });

            modelBuilder.Entity("LegislativeInfoSystem.Entities.Legislator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hometown")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Legislators");
                });

            modelBuilder.Entity("LegislationLegislator", b =>
                {
                    b.HasOne("LegislativeInfoSystem.Entities.Legislation", null)
                        .WithMany()
                        .HasForeignKey("LegislationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislativeInfoSystem.Entities.Legislator", null)
                        .WithMany()
                        .HasForeignKey("SponsorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
